#!/bin/bash

warn () { echo -e "$1" >&2; }

usage() {
  cat <<EOD
Usage: passenger-app <app> <command> [<args>]

Commands:
   start     Start application <app>
   reload    Reload application <app>
   stop      Stop application <app>
   restart   Restart application <app>
   status    Run passenger-status with <args>
   config    Run passenger-config with <args>
EOD
}

config() {
  exec passenger-config "$@"
}

status() {
  exec passenger-status "$@"
}

start() {
  cd "$APPDIR"
  exec ${PASSENGER_ROOT}/bin/passenger start current --daemonize --instance-registry-dir ${PASSENGER_INSTANCE_REGISTRY_DIR} --engine builtin --socket ${PASSENGER_INSTANCE_REGISTRY_DIR}/app.sock --pid-file ${PASSENGER_INSTANCE_REGISTRY_DIR}/app.pid --log-file ${APPDIR}/shared/log/passenger.log --environment production $PASSENGER_OPTS
}

reload() {
  exec passenger-config restart-app "$APPDIR"
}

stop() {
  exec ${PASSENGER_ROOT}/bin/passenger stop --pid-file ${PASSENGER_INSTANCE_REGISTRY_DIR}/app.pid
}

restart() {
  echo "Shutting down application ..."
  ${PASSENGER_ROOT}/bin/passenger stop --pid-file ${PASSENGER_INSTANCE_REGISTRY_DIR}/app.pid
  sleep 5
  start
}

APP=$1; shift
ACTION=$1; shift

# sanity checks
[ ! "$APP" ] && warn "Please specify the application to use" && exit 1

if [ "$APP" == "--help" ]; then
  usage && exit 0
fi

if [ ! -n "$PASSENGER_APPS_ROOT" ]; then
  PASSENGER_APPS_ROOT="/srv/apps"
fi

if [ ! -d "$PASSENGER_APPS_ROOT" ]; then
  warn "Passenger applications root not found at $PASSENGER_APPS_ROOT"
  warn "Check the PASSENGER_APPS_ROOT environment variable"
  exit 1
fi

APPDIR="$PASSENGER_APPS_ROOT/$APP"
if [ ! -d "$APPDIR" ]; then
  warn "Application $APP not found at $APPDIR"
  exit 1
fi

PASSENGER_INSTANCE_REGISTRY_DIR="$APPDIR/passenger"
if [ ! -d "$PASSENGER_INSTANCE_REGISTRY_DIR" ]; then
  warn "Passenger instance registry not found at $PASSENGER_INSTANCE_REGISTRY_DIR"
  exit 1
fi

PASSENGER_ENV="$APPDIR/current/config/passenger.env"
if [ ! -f "$PASSENGER_ENV" ]; then
  warn "Passenger environment not found at $PASSENGER_ENV"
  exit 1
fi

source $PASSENGER_ENV

# TODO: check env variables

export PATH
export GEM_HOME
export GEM_PATH
export PASSENGER_ROOT
export PASSENGER_OPTS
export PASSENGER_INSTANCE_REGISTRY_DIR
  
case "$ACTION" in
  help)
    usage && exit 0
  ;;
  start)
    start
  ;;
  reload)
    reload
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  status)
    status $@
  ;;
  config)
    config $@
  ;;
  *)
    usage && exit 1
  ;;
esac

